### ISSUE TITLE
Path is not qualified although it is!

### ISSUE THREAD

**Issue by jsuarezm** [dsestero/jboss#1]
Hi,
I have the following error: 
Error: Failed to apply catalog: Validation of Exec[copy_profile_instance] failed: 'cp -a /opt/jboss-4.2.3.GA/server/default /opt/jboss-4.2.3.GA/server/instance' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/code/environments/production/modules/jboss/manifests/instance_4/install.pp:25
I think is necessary to specify a path param for the cp command.

Regards,
Jesús A. Suárez

**Comment by dsestero** [comment]
Hi,
sorry I come to you after all this time but I missed the notification and see the issue just now.
I cannot reproduce the problem on Ubuntu 14.04 by creating a Jboss-4.2.3 instance with the latest version (v2.1.2) of the jboss module. Here my test configuration:
```
class inva::jboss::instance::test_4_2_3 {
  include jboss, java::java_6
  jboss::instance_4 { 'test':
    version     => '4.2.3',
    profile     => 'default',
    environment => 'test',
    mgmt_user   => 'admin',
    mgmt_passwd => changeme',
    jmx_user    => 'jmxusr',
    jmx_passwd  => 'jmxpsw',
  }
}
```
Could you please provide more details about your configuration in order to reproduce the problem?

**Comment by tealecloud** [comment]
Seeing a similar problem on Puppet: 4.10.12 - OEL 7

**Comment by dsestero** [comment]
Approved the PR from tealecloud
